boulder: Add support for compressman option
AerynOS/os-tools pull request #281
Opened 2024-07-17 23:54 UTC by joebonrichie

Compresses any man/info pages with zstd. A tradeoff between slightly bigger .stone files vs smaller installed size.

Tested 
- `nano` (contains man and info files)
- `xz` (contains lots of man symlinks)

2024-07-18 21:56 UTC, ReillyBrogan commented on boulder/src/package/analysis/handler.rs
> +        let input = File::create(&output_path).unwrap();
`.unwrap()` will panic if the `Result` has an object, which is not a good idea and you should avoid using it.

Instead, you can use `?` (see [here](https://doc.rust-lang.org/rust-by-example/std/result/question_mark.html)) to automatically handle unwrap and handle errors. If a function returns an error it will automatically unwrap it if it's not an error and continue, and if it is an error it will propagate it upwards. This requires that the function with `?` returns a `Result`, but you're already doing that.

So
```
        let input = File::create(&output_path).unwrap();
```
would become
```
        let input = File::create(&output_path)?;
```

Use this pattern every where you are currently doing an unwrap and profit.

2024-07-18 22:03 UTC, ReillyBrogan commented on boulder/src/package/analysis/handler.rs
> +        let mut reader = BufReader::new(File::open(path).unwrap());
```
        let mut reader = BufReader::new(File::open(path)?);
```

2024-07-18 22:05 UTC, ReillyBrogan commented on boulder/src/package/analysis/handler.rs
> +        use zstd::stream::copy_encode;
I assume you copied this section from somewhere:
- Don't use `extern crate zstd;`. All it's doing is allowing you to use `copy_encode()` without the zstd namespace, but that's not actually all that useful. You should just be able to use `zstd::copy_encode()` after removing it (and having the correct imports)
- Move the `use` statements above and merge with the existing imports

2024-07-20 09:52 UTC, livingsilver94 requested changes
Although I'm not a Rust expert, let's try to make this code more idiomatic by using the Path/PathBuf structs.

2024-07-20 09:52 UTC, livingsilver94 commented on boulder/src/package/analysis/handler.rs
> +            symlink(format!("{}.zst", fs::read_link(&file_path)?.display()), &new_link).unwrap_or_else(|why| {
This is pretty convoluted. Since `fs::read_link` returns a `Result` contaning a `PathBuf`, can you just do `fs::read_link(&file_path)?.set_extension("zst")` ?
 
[Example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=018c6a785cdeaac4924d2a869b28315d) here.

2024-07-20 09:52 UTC, livingsilver94 commented on boulder/src/package/analysis/handler.rs
> +    let file_path = info.path.clone().into_os_string().into_string().unwrap_or_default();
Do you need this to be a String, instead of a Path or PathBuf? I see that below you're calling `contains`, `ends_with` and other string operations like these.

As an example, the `contains` function can be replicated by calling `components`, which is an iterator, and then by checking if the iterator contains `man`. `ends_with` could be checking whether the extension of `file_path.file_name()` (which returns the last component of the path) or the full name is what you expect.

2024-07-20 09:52 UTC, livingsilver94 commented on boulder/src/package/analysis/handler.rs
> +            /*
C-like comments are meh in my opinion. Double slashes ftw.

2024-07-20 20:15 UTC, joebonrichie commented on boulder/src/package/analysis/handler.rs
> +            symlink(format!("{}.zst", fs::read_link(&file_path)?.display()), &new_link).unwrap_or_else(|why| {
set_extension returns a bool so no longer a one liner

2024-07-21 16:02 UTC, joebonrichie commented on boulder/src/package/analysis/handler.rs
> +            symlink(format!("{}.zst", fs::read_link(&file_path)?.display()), &new_link).unwrap_or_else(|why| {
`with_extension()` is a no-go as it replaces 1..9 with the extension.

2024-08-19 12:45 UTC, joebonrichie commented
Should be good now

2024-09-12 20:23 UTC, joebonrichie commented
:ping_pong:

2025-01-17 20:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/serpent-os/tools?pullRequest=281) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/serpent-os/tools?pullRequest=281) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/serpent-os/tools?pullRequest=281) it.</sub>

2025-05-08 17:44 UTC, ermo requested changes
Needs a rebase. I am aware that this is inconvenient and that it's been sitting for _way_ too long in the queue.

2025-05-08 17:53 UTC, ermo requested changes
Needs rebase sadly.

2025-05-09 11:12 UTC, joebonrichie commented
replaced by #475

2025-05-09 11:12 UTC, closed without merging